stages:
  - build

before_script:
  - apt-get update -qy
  - apt-get install -y clang
  - apt-get install -y clang-format
  - apt-get install -y make
  - apt-get install libreadline-dev

build:
  stage: build
  script:
    - make build
